### ISSUE TITLE
tested platforms ?

### ISSUE THREAD

**Issue by delahee** [ciscoheat/slambda#2]
Hi pal !

Can you document on what platforms slambda is tested please ? 

Thanks !

**Comment by ciscoheat** [comment]
Hello! Slambda is tested together with the Buddy library, and the tests are passing on all supported platforms: cpp, cs, java, js, neko, js/node, php and flash.

Here's the latest Travis build result: https://travis-ci.org/ciscoheat/buddy

**Comment by delahee** [comment]
Awesome !

**Comment by fullofcaffeine** [comment]
Great work, Andreas!

**Comment by ciscoheat** [comment]
Thanks Marcelo and David :)
